version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django_app

  django_app:
    container_name: django_app
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env